<!DOCTYPE html>
<head>
 <link href="<?php echo HOME_URL; ?>css/getsvgimage.css" media="all" rel="stylesheet" type="text/css" />
 <script src="<?php echo HOME_URL; ?>includes/js/jquery-2.0.3.min.js"></script>
  <script src="<?php echo HOME_URL; ?>includes/js/report.js"></script>
</head>
<body>
 <div id ="chart_area">
	<h2>From CLASS</h2>
	<?php echo $chart_image1 ; ?>
	<?php echo $chart_image2 ; ?>
		<?php echo $chart_image3 ; ?>
			<?php echo $chart_image4 ; ?>
		<?php echo $chart_image5 ; ?>
	<?php echo $chart_image6 ; ?>
	<?php echo $chart_image7 ; ?>
	<?php echo $chart_image8 ; ?>
	<?php echo $chart_image9 ; ?>
  <?php echo $chart_image10 ; ?>
 </div>
</body>
</html>