<?php

 class hr_employee_termination_ss extends hr_employee_termination {

   public static $system_info = [
  'name' => 'SS - Employee Termination ',
  'number' => '3117',
  'description' => 'Self Service Employee Termination',
  'version' => '0.1.1',
  'db_version' => '1001',
  'mod_version' => '1.1.1',
  'primary_entity_cb' => '',
  'module_name' => 'sys',
  'weight' => 7
 ];

 }

//end of hr_employee_termination class
?>