<?php  
defined("SMTP_HOST") ? null : define("SMTP_HOST", "mail.coherent.com"); 
defined("SMTP_PORT") ? null : define("SMTP_PORT", "465"); 
defined("SMTP_USERNAME") ? null : define("SMTP_USERNAME", "asia\dasn"); 
defined("SMTP_PASSWORD") ? null : define("SMTP_PASSWORD", "Sep@2013"); 
defined("SMTP_FROMEMAIL") ? null : define("SMTP_FROMEMAIL", "nishit.das@coherent.com"); 

//defined("SMTP_HOST") ? null : define("SMTP_HOST", "smtp.gmail.com"); 
//defined("SMTP_PORT") ? null : define("SMTP_PORT", "465"); 
//defined("SMTP_USERNAME") ? null : define("SMTP_USERNAME", "ndas.oracle@gmail.com"); 
//defined("SMTP_PASSWORD") ? null : define("SMTP_PASSWORD", "subhanish@01"); 
?>