<?php

foreach ($prj_rate_schedule_line_object as &$prj_rate_schedule_line) {
// switch ($prj_rate_schedule_line->resource_type) {
//  case 'HR_EMPLOYEE' :
//   $emp_details = hr_employee::find_by_id($prj_rate_schedule_line->hr_employee_id);
//   $prj_rate_schedule_line->employee_name = $emp_details->first_name . ' ' . $emp_details->last_name;
//   break;
//
//  default:
//  $prj_rate_schedule_line->employee_name = null;
//   break;
// }
}


?>