<?php

/**
 * inoERP
 *
 * @copyright   2014 Nishit R. Das
 * @license     https://www.mozilla.org/MPL/2.0/
 * @link        http://inoideas.org
 * @source code https://github.com/inoerp/inoERP
 */

/**
 * ec_order_success
 * 
 * 
 */
// public $rev_enabled_cb;  needs to be dropped - use ec_order_success rev only

class ec_order_success extends ec_paid_order {



}

//end of ec_order_success class
?>